/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airline_reservation_system;

import static java.awt.Color.blue;

/**
 *
 * @author Asus
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.getContentPane().setBackground(blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addcustomer = new javax.swing.JMenuItem();
        searchcustomer = new javax.swing.JMenuItem();
        addflight = new javax.swing.JMenu();
        add_flight = new javax.swing.JMenuItem();
        bookflight = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        viewticket = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        addadmin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        jMenu1.setText("Customer");

        addcustomer.setText("Add Customer");
        addcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustomerActionPerformed(evt);
            }
        });
        jMenu1.add(addcustomer);

        searchcustomer.setText("Search Customer");
        searchcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcustomerActionPerformed(evt);
            }
        });
        jMenu1.add(searchcustomer);

        jMenuBar1.add(jMenu1);

        addflight.setText("Flight");

        add_flight.setText("Add Flight");
        add_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_flightActionPerformed(evt);
            }
        });
        addflight.add(add_flight);

        bookflight.setText("Book Flight");
        bookflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookflightActionPerformed(evt);
            }
        });
        addflight.add(bookflight);

        jMenuBar1.add(addflight);

        jMenu3.setText("Ticket");

        viewticket.setText("View Ticket");
        viewticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewticketActionPerformed(evt);
            }
        });
        jMenu3.add(viewticket);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Admin");

        addadmin.setText("Add Admin");
        addadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addadminActionPerformed(evt);
            }
        });
        jMenu4.add(addadmin);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_flightActionPerformed
        // TODO add your handling code here:
        AddFlight flight = new AddFlight();
        Desktop.add(flight);
        flight.setVisible(true);
        
    }//GEN-LAST:event_add_flightActionPerformed

    private void addcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustomerActionPerformed
        // TODO add your handling code here:
        Addcustomer customer = new Addcustomer();
        Desktop.add(customer);
        customer.setVisible(true);
    }//GEN-LAST:event_addcustomerActionPerformed

    private void searchcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcustomerActionPerformed
        // TODO add your handling code here:
        SearchCustomer search = new SearchCustomer();
        Desktop.add(search);
        search.setVisible(true);
    }//GEN-LAST:event_searchcustomerActionPerformed

    private void bookflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookflightActionPerformed
        // TODO add your handling code here:
        BookTicket book = new BookTicket();
        Desktop.add(book);
        book.setVisible(true);
    }//GEN-LAST:event_bookflightActionPerformed

    private void viewticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewticketActionPerformed
        // TODO add your handling code here:
        GetTicket ticket = new GetTicket();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_viewticketActionPerformed

    private void addadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addadminActionPerformed
        // TODO add your handling code here:
        AddAdmin admin = new AddAdmin();
        Desktop.add(admin);
        admin.setVisible(true);
    }//GEN-LAST:event_addadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem add_flight;
    private javax.swing.JMenuItem addadmin;
    private javax.swing.JMenuItem addcustomer;
    private javax.swing.JMenu addflight;
    private javax.swing.JMenuItem bookflight;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem searchcustomer;
    private javax.swing.JMenuItem viewticket;
    // End of variables declaration//GEN-END:variables
}
